# Generated by Django 4.0.5 on 2022-08-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_value', models.CharField(max_length=250, verbose_name='Ответы в свободной форме')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, verbose_name='Департамент')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('website', models.CharField(max_length=30, verbose_name='Сайт')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.departments', verbose_name='Parent_id')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField(verbose_name='Дата проведения оценки')),
            ],
        ),
        migrations.CreateModel(
            name='Form_Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование разделов')),
                ('version', models.CharField(max_length=20, verbose_name='Версия раздела')),
                ('order_num', models.IntegerField(verbose_name='Порядковый номер')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование формы Акта/Отчета')),
                ('version', models.CharField(max_length=20, verbose_name='Версия формы')),
                ('created_at', models.DateField(verbose_name='Дата формы')),
                ('departments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.departments', verbose_name='Департаменты_id')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Вопросы')),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.IntegerField(verbose_name='Квота респондентов')),
            ],
            options={
                'verbose_name': 'Квота',
                'verbose_name_plural': 'Квоты',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Рекоммендации')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование шаблона html')),
                ('template_file', models.FileField(upload_to='', verbose_name='Ссылка на шаблон')),
                ('version', models.CharField(max_length=20, verbose_name='Версия шаблона')),
            ],
        ),
        migrations.CreateModel(
            name='Signed_Dociuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='Наименования документов')),
                ('originat_file_name', models.FileField(upload_to='', verbose_name='Ссылка на документ')),
                ('description', models.CharField(max_length=250, verbose_name='Комментарий')),
                ('created_at', models.DateField(verbose_name='Дата документа')),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.evaluation', verbose_name='Оценка_id')),
                ('forms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.forms', verbose_name='Формы_id')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=50, verbose_name='Варианты ответов')),
                ('questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.questions', verbose_name='Вопросы_id')),
            ],
        ),
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=200, verbose_name='Учреждение')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('website', models.CharField(max_length=30, verbose_name='Сайт')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.departments', verbose_name='Департамент_id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Parent_id')),
                ('quota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.quota', verbose_name='Квота_id')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
            },
        ),
        migrations.CreateModel(
            name='Organisation_Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Учреждение_id')),
            ],
            options={
                'verbose_name': 'Ответственный из Учреждения',
                'verbose_name_plural': 'Ответственные из Учреждений',
            },
        ),
        migrations.CreateModel(
            name='Forms_Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_value', models.CharField(max_length=250, verbose_name='Рекомендации в свободной форме')),
                ('answers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.answers', verbose_name='Ответы_id')),
                ('form_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.form_sections', verbose_name='Разделы_id')),
                ('forms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.forms', verbose_name='Формы_id')),
                ('recommendations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.recommendations', verbose_name='Рекоммендации_id')),
            ],
        ),
        migrations.AddField(
            model_name='forms',
            name='templates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.templates', verbose_name='Шаблоны_id'),
        ),
        migrations.CreateModel(
            name='Form_Sections_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(verbose_name='Порядковый номер')),
                ('forms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.forms', verbose_name='Формы_id')),
                ('questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.questions', verbose_name='Вопросы_id')),
            ],
        ),
        migrations.AddField(
            model_name='form_sections',
            name='forms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.forms', verbose_name='Формы_id'),
        ),
        migrations.AddField(
            model_name='form_sections',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.form_sections', verbose_name='Parent_id'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='forms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.forms', verbose_name='Формы_id'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='organisation_persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisation_persons', verbose_name='Представитель организации_id'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='organisations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Организации_id'),
        ),
        migrations.AddField(
            model_name='departments',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.regions', verbose_name='Регион_id'),
        ),
        migrations.CreateModel(
            name='Department_Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.departments', verbose_name='Департамент_id')),
            ],
            options={
                'verbose_name': 'Ответственный из Департамента',
                'verbose_name_plural': 'Ответственные из Департаментов',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='forms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.forms', verbose_name='Формы_id'),
        ),
        migrations.AddField(
            model_name='answers',
            name='organisations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Организации_id'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question_values',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.question_values', verbose_name='Варианты ответов_id'),
        ),
        migrations.AddField(
            model_name='answers',
            name='questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.questions', verbose_name='Вопросы_id'),
        ),
        migrations.AddField(
            model_name='answers',
            name='quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.quota', verbose_name='Квоты_id'),
        ),
    ]
