# Generated by Django 4.0.5 on 2022-08-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_department', models.CharField(max_length=100, verbose_name='Департамент')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('tel', models.CharField(max_length=15, verbose_name='Телефон')),
                ('website', models.CharField(max_length=30, verbose_name='Сайт')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('fio_responsible', models.CharField(max_length=50, verbose_name='Ответственное лицо')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.region', verbose_name='Регион_id')),
            ],
        ),
    ]
