# Generated by Django 4.0.5 on 2022-08-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Типы ответов')),
            ],
            options={
                'verbose_name_plural': 'Тип ответа',
            },
        ),

        migrations.AddField(
            model_name='questions',
            name='type_answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_answers', verbose_name='Тип вопроса_id'),
        ),

    ]
