# Generated by Django 4.0.5 on 2022-08-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, verbose_name='Таблица')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('active', models.BooleanField(default=True, verbose_name='Состояние')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
            ],
            options={
                'verbose_name_plural': 'Контроль версий',
            },
        ),
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Ответы - факт'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name_plural': 'Независимая оценка'},
        ),
        migrations.AlterModelOptions(
            name='form_sections',
            options={'verbose_name_plural': 'Наименование разделов'},
        ),
        migrations.AlterModelOptions(
            name='form_sections_question',
            options={'verbose_name_plural': 'Сопоставление вопрос-форма'},
        ),
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name_plural': 'Наименование формы Акта/Отчета'},
        ),
        migrations.AlterModelOptions(
            name='forms_recommendations',
            options={'verbose_name_plural': 'Рекомендации - факт'},
        ),
        migrations.AlterModelOptions(
            name='question_values',
            options={'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'Варианты вопросов'},
        ),
        migrations.AlterModelOptions(
            name='recommendations',
            options={'verbose_name_plural': 'Варианты рекоммендаций'},
        ),
        migrations.AlterModelOptions(
            name='signed_dociuments',
            options={'verbose_name_plural': 'Подписанные Акты'},
        ),
        migrations.AlterModelOptions(
            name='templates',
            options={'verbose_name': 'Наименование шаблона html', 'verbose_name_plural': 'Наименование шаблона html'},
        ),
        migrations.AddField(
            model_name='answers',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='department_persons',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='departments',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='form_sections',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='form_sections_question',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='forms',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='forms_recommendations',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='organisation_persons',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='organisations',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='questions',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='regions',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='signed_dociuments',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='templates',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.versions', verbose_name='Версия_id'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.versions', verbose_name='Версия_id'),
        ),
    ]
