# Generated by Django 4.0.5 on 2022-08-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_versions_alter_answers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versions',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Текущая версия'),
        ),
    ]
