# Generated by Django 4.0.5 on 2022-09-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_type_answers_type_departments_type_organisations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип департамента')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
            ],
            options={
                'verbose_name': 'Тип департамента',
                'verbose_name_plural': 'Типы департаментов',
            },
        ),
        migrations.CreateModel(
            name='Type_Organisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип учреждения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
            ],
            options={
                'verbose_name': 'Тип учреждения',
                'verbose_name_plural': 'Типы учреждений',
            },
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, verbose_name='Таблица')),
                ('version', models.CharField(max_length=50, verbose_name='Версия')),
                ('active', models.BooleanField(default=True, verbose_name='Текущая версия')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
            ],
            options={
                'verbose_name_plural': 'Контроль версий',
            },
        ),
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Ответы - факт'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name_plural': 'Независимая оценка'},
        ),
        migrations.AlterModelOptions(
            name='form_sections',
            options={'verbose_name_plural': 'Наименование разделов'},
        ),
        migrations.AlterModelOptions(
            name='form_sections_question',
            options={'verbose_name_plural': 'Сопоставление вопрос-форма'},
        ),
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name_plural': 'Наименование формы Акта/Отчета'},
        ),
        migrations.AlterModelOptions(
            name='forms_recommendations',
            options={'verbose_name_plural': 'Рекомендации - факт'},
        ),
        migrations.AlterModelOptions(
            name='question_values',
            options={'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'Варианты вопросов'},
        ),
        migrations.AlterModelOptions(
            name='recommendations',
            options={'verbose_name_plural': 'Варианты рекоммендаций'},
        ),
        migrations.AlterModelOptions(
            name='signed_dociuments',
            options={'verbose_name_plural': 'Подписанные Акты'},
        ),
        migrations.AlterModelOptions(
            name='templates',
            options={'verbose_name': 'Наименование шаблона html', 'verbose_name_plural': 'Наименование шаблона html'},
        ),
        migrations.RemoveField(
            model_name='forms',
            name='departments',
        ),
        migrations.AddField(
            model_name='answers',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='department_persons',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='departments',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='form_sections',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='form_sections_question',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='forms',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='forms_recommendations',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='organisation_persons',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='organisations',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='questions',
            name='form_sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.form_sections', verbose_name='Наименование разделов_id'),
        ),
        migrations.AddField(
            model_name='questions',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='regions',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='signed_dociuments',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AddField(
            model_name='templates',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
        migrations.AlterField(
            model_name='form_sections',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование разделов'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='templates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.templates', verbose_name='Шаблоны_id'),
        ),
        migrations.AlterField(
            model_name='forms_recommendations',
            name='free_value',
            field=models.CharField(max_length=300, verbose_name='Рекомендации в свободной форме'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Рекоммендации'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='Фото')),
                ('original_file_name', models.CharField(max_length=50, verbose_name='Оригинальное имя файла')),
                ('description', models.CharField(max_length=50, verbose_name='Комментарий')),
                ('created_at', models.DateField(verbose_name='Дата документа')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.evaluation', verbose_name='Оценка_id')),
                ('forms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.forms', verbose_name='Формы_id')),
            ],
            options={
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_value', models.CharField(max_length=300, verbose_name='Комментарии')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('forms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.forms', verbose_name='Формы_id')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='type_departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента_id'),
        ),
        migrations.AddField(
            model_name='form_sections',
            name='type_departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента_id'),
        ),
        migrations.AddField(
            model_name='forms',
            name='type_departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента_id'),
        ),
        migrations.AddField(
            model_name='organisations',
            name='type_organisations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения_id'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.versions', verbose_name='Версия_id'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.versions', verbose_name='Версия_id'),
        ),
    ]
