# Generated by Django 4.0.5 on 2022-08-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_versions_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип департамента')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
            ],
            options={
                'verbose_name': 'Тип департамента',
                'verbose_name_plural': 'Типы департаментов',
            },
        ),
        migrations.CreateModel(
            name='Type_Organisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип учреждения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
            ],
            options={
                'verbose_name': 'Тип учреждения',
                'verbose_name_plural': 'Типы учреждений',
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='type_departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента_id'),
        ),
        migrations.AddField(
            model_name='organisations',
            name='type_organisations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения_id'),
        ),
    ]
