# Generated by Django 4.0.5 on 2022-08-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_type_departments_type_organisations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='departments',
        ),
        migrations.AddField(
            model_name='forms',
            name='type_departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента_id'),
        ),
        migrations.AlterField(
            model_name='form_sections',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование разделов'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='templates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.templates', verbose_name='Шаблоны_id'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.versions', verbose_name='Версия_id'),
        ),
        migrations.AlterField(
            model_name='forms_recommendations',
            name='free_value',
            field=models.CharField(max_length=300, verbose_name='Рекомендации в свободной форме'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='type_organisations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения_id'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Рекоммендации'),
        ),
    ]
