# Generated by Django 4.0.5 on 2022-09-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_photo_user_signed_dociuments_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_exchange',
            name='date_exchange',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения данных'),
        ),
    ]
