# Generated by Django 4.0.5 on 2022-10-06 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_departments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_values',
            name='questions',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_variant',
            field=models.JSONField(blank=True, max_length=500, null=True, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type_answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_answers', verbose_name='Тип ответа_id'),
        ),
    ]
