# Generated by Django 4.0.5 on 2022-10-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_remove_question_values_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_values',
            name='value_name',
            field=models.CharField(max_length=200, verbose_name='Варианты ответов'),
        ),
    ]
