# Generated by Django 4.0.5 on 2022-10-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_alter_question_values_value_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_variant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вариант ответа'),
        ),
    ]
