# Generated by Django 4.0.5 on 2022-10-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0010_alter_comments_free_value_alter_departments_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='type_organisations',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Принадлежность к типу организаций'),
        ),
    ]
