# Generated by Django 4.0.5 on 2022-11-05 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0011_questions_type_organisations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListForCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя списка')),
                ('period', models.CharField(max_length=100, null=True, verbose_name='Период проверки')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.departments', verbose_name='Департамент_id')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Учреждение_id')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.regions', verbose_name='Регион_id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Списки проверяемых организаций',
            },
        ),
        migrations.CreateModel(
            name='FormsAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_json', models.JSONField(verbose_name='Структура акта')),
                ('version', models.CharField(max_length=50, null=True, verbose_name='Версия формы акта')),
                ('type_departments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента_id')),
                ('type_organisations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения_id')),
            ],
            options={
                'verbose_name_plural': 'Формы актов',
            },
        ),
    ]
