# Generated by Django 4.0.5 on 2022-11-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_alter_formsact_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form_sections_question',
            options={'verbose_name_plural': 'Сопоставление вопрос-раздел'},
        ),
        migrations.RemoveField(
            model_name='form_sections_question',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='form_sections_question',
            name='questions',
        ),
        migrations.AddField(
            model_name='form_sections_question',
            name='answer_variant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вариант ответа'),
        ),
        migrations.AddField(
            model_name='form_sections_question',
            name='form_sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.form_sections', verbose_name='Наименование разделов_id'),
        ),
        migrations.AddField(
            model_name='form_sections_question',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='checklist.questions', verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form_sections_question',
            name='type_answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_answers', verbose_name='Тип ответа_id'),
        ),
        migrations.AddField(
            model_name='form_sections_question',
            name='type_organisations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения_id'),
        ),
        migrations.AlterField(
            model_name='form_sections_question',
            name='order_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
