# Generated by Django 4.0.5 on 2022-11-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0015_rename_name_questions_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_sections_question',
            name='type_organisations',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип учреждения_id'),
        ),
    ]
