# Generated by Django 4.0.5 on 2022-11-11 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0016_alter_form_sections_question_type_organisations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование проверки')),
                ('date_checking', models.DateField(verbose_name='Дата проверки')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.departments', verbose_name='Департамент')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name_plural': 'Наименование проверки',
            },
        ),
        migrations.CreateModel(
            name='List_Checking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('checking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.checking', verbose_name='Наименование проверки')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Учреждение')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
            ],
            options={
                'verbose_name_plural': 'Проверяемые организации',
            },
        ),
        migrations.DeleteModel(
            name='ListForCheck',
        ),
    ]
