# Generated by Django 4.0.5 on 2022-11-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0020_alter_question_values_name_alternativ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='templates',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='type_departments',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='version',
        ),
        migrations.AlterModelOptions(
            name='form_sections',
            options={'verbose_name_plural': 'Наименование разделов акта'},
        ),
        migrations.AlterModelOptions(
            name='templates',
            options={'verbose_name': 'Шаблоны html', 'verbose_name_plural': 'Шаблоны html'},
        ),
        migrations.AlterModelOptions(
            name='type_answers',
            options={'verbose_name': 'Тип ответа', 'verbose_name_plural': 'Типы ответов'},
        ),
        migrations.RemoveField(
            model_name='answers',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question_values',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='quota',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='form_sections',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='forms_recommendations',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='signed_dociuments',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='signed_dociuments',
            name='forms',
        ),
        migrations.AddField(
            model_name='answers',
            name='answers_json',
            field=models.JSONField(null=True, verbose_name='Структура ответов'),
        ),
        migrations.AddField(
            model_name='answers',
            name='checking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.checking', verbose_name='Проверка_id'),
        ),
        migrations.AddField(
            model_name='formsact',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата формы акта'),
        ),
        migrations.AddField(
            model_name='list_checking',
            name='organisation_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisation_persons', verbose_name='Представитель организации'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='free_value',
            field=models.JSONField(verbose_name='Ответы в свободной форме'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='transaction_exchange',
            name='new_data',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Новые данные'),
        ),
        migrations.AlterField(
            model_name='transaction_exchange',
            name='old_data',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Старые данные'),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='Forms',
        ),
    ]
