# Generated by Django 4.0.5 on 2022-11-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0021_remove_forms_templates_remove_forms_type_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='free_value',
        ),
        migrations.AlterField(
            model_name='templates',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.versions', verbose_name='Версия_id'),
        ),
    ]
