# Generated by Django 4.0.5 on 2022-11-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0023_templates_type_organisations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_checking',
            options={'verbose_name': 'Проверяемая организация', 'verbose_name_plural': 'Проверяемые организации'},
        ),
        migrations.AlterField(
            model_name='answers',
            name='checking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.checking', verbose_name='Проверка'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='organisations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Организации'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.departments', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.departments', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.regions', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='type_departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента'),
        ),
        migrations.AlterField(
            model_name='form_sections',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.form_sections', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='form_sections',
            name='type_departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента'),
        ),
        migrations.AlterField(
            model_name='form_sections_question',
            name='form_sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.form_sections', verbose_name='Наименование разделов'),
        ),
        migrations.AlterField(
            model_name='form_sections_question',
            name='type_answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_answers', verbose_name='Тип ответа'),
        ),
        migrations.AlterField(
            model_name='form_sections_question',
            name='type_organisations',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип учреждения'),
        ),
        migrations.AlterField(
            model_name='forms_recommendations',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.answers', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='forms_recommendations',
            name='form_sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.form_sections', verbose_name='Разделы'),
        ),
        migrations.AlterField(
            model_name='forms_recommendations',
            name='recommendations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.recommendations', verbose_name='Рекоммендации'),
        ),
        migrations.AlterField(
            model_name='formsact',
            name='type_departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента'),
        ),
        migrations.AlterField(
            model_name='formsact',
            name='type_organisations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.departments', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.quota', verbose_name='Квота'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='type_organisations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения'),
        ),
    ]
