# Generated by Django 4.0.5 on 2022-11-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0024_alter_list_checking_options_alter_answers_checking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation_persons',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность'),
        ),
    ]
