# Generated by Django 4.0.5 on 2022-11-28 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0025_alter_organisation_persons_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_checking',
            name='organisation_person',
        ),
        migrations.RemoveField(
            model_name='organisation_persons',
            name='organisation',
        ),
        migrations.AlterField(
            model_name='answers',
            name='answers_json',
            field=models.JSONField(null=True, verbose_name='Результаты ответов'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='forms_recommendations',
            name='form_sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.form_sections', verbose_name='Разделы'),
        ),
        migrations.AlterField(
            model_name='forms_recommendations',
            name='recommendations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.recommendations', verbose_name='Рекоммендации'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='question_values',
            name='name_alternativ',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Альтернативный вариант ответа'),
        ),
        migrations.AlterField(
            model_name='type_organisations',
            name='type_departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_departments', verbose_name='Тип департамента'),
        ),
        migrations.CreateModel(
            name='Form_Organisation_Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Учреждение')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisation_persons', verbose_name='Учреждение')),
            ],
            options={
                'verbose_name': 'Сопоставление Ответственный --> Учреждение',
                'verbose_name_plural': 'Сопоставление Ответственный --> Учреждение',
            },
        ),
    ]
