# Generated by Django 4.0.5 on 2022-11-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0026_remove_list_checking_organisation_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_organisation_persons',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisation_persons', verbose_name='Ответственный'),
        ),
    ]
