# Generated by Django 4.0.5 on 2022-12-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0027_alter_form_organisation_persons_person'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organisation_persons',
            constraint=models.UniqueConstraint(fields=('first_name', 'second_name', 'last_name', 'position', 'phone', 'email'), name='unique_person'),
        ),
    ]
