# Generated by Django 4.0.5 on 2022-12-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0028_organisation_persons_unique_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='id_questions',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Список id вопросов'),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='id_type_departments',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Список id департаментов'),
        ),
    ]
