# Generated by Django 4.0.5 on 2022-12-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0030_form_organisation_persons_unique_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Type_Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Учреждение')),
                ('type_organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения')),
            ],
            options={
                'verbose_name_plural': 'Сопоставление Учреждение --> Тип',
            },
        ),
        migrations.AddConstraint(
            model_name='form_type_organisation',
            constraint=models.UniqueConstraint(fields=('organisation', 'type_organisation'), name='unique_typeorg'),
        ),
    ]
