# Generated by Django 4.0.5 on 2022-12-07 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0031_form_type_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='type_organisations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения'),
        ),
    ]
