# Generated by Django 4.0.5 on 2022-12-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0032_answers_type_organisations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answers',
            constraint=models.UniqueConstraint(fields=('organisations', 'type_organisations', 'checking'), name='unique_answers'),
        ),
    ]
