# Generated by Django 4.0.5 on 2022-12-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0034_remove_organisations_type_organisations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_persons',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email'),
        ),
    ]
