# Generated by Django 4.0.5 on 2022-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0035_alter_department_persons_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_persons',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='second_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='website',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='form_sections_question',
            name='answer_variant',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='form_sections_question',
            name='type_organisations',
            field=models.CharField(blank=True, max_length=50, verbose_name='id Типов учреждений'),
        ),
        migrations.AlterField(
            model_name='formsact',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата формы акта'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='second_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='website',
            field=models.CharField(blank=True, max_length=30, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='question_values',
            name='name_alternativ',
            field=models.CharField(blank=True, max_length=100, verbose_name='Альтернативный вариант ответа'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='id_questions',
            field=models.CharField(blank=True, max_length=50, verbose_name='Список id вопросов'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='id_type_departments',
            field=models.CharField(blank=True, max_length=20, verbose_name='Список id департаментов'),
        ),
    ]
