# Generated by Django 4.0.5 on 2022-12-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0040_list_checking_date_check_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_checking',
            name='person',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisation_persons', verbose_name='Ответственный'),
            preserve_default=False,
        ),
    ]
