# Generated by Django 4.0.5 on 2023-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0044_alter_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsact',
            name='act_json_to_calculate',
            field=models.JSONField(blank=True, default=1, verbose_name='Структура для расчета рейтинга'),
            preserve_default=False,
        ),
    ]
