# Generated by Django 4.0.5 on 2023-01-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0045_formsact_act_json_to_calculate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisations',
            name='quota',
        ),
        migrations.AddField(
            model_name='answers',
            name='quota',
            field=models.IntegerField(default=1, verbose_name='Количество получателей услуг'),
        ),
    ]
