# Generated by Django 4.0.5 on 2023-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0046_remove_organisations_quota_answers_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='invalid_person',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество инвалидов'),
        ),
        migrations.AddField(
            model_name='organisations',
            name='inn',
            field=models.IntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='organisations',
            name='kpp',
            field=models.IntegerField(blank=True, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='organisations',
            name='ogrn',
            field=models.IntegerField(blank=True, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Юридический Адрес'),
        ),
    ]
