# Generated by Django 4.0.5 on 2023-02-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0047_answers_invalid_person_organisations_inn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_json', models.JSONField(null=True, verbose_name='Результаты рейтинговой оценки')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('checking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.checking', verbose_name='Проверка')),
                ('organisations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Организации')),
                ('type_organisations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_organisations', verbose_name='Тип учреждения')),
            ],
            options={
                'verbose_name_plural': 'Рейтинговая оценка - ИТОГО',
            },
        ),
        migrations.DeleteModel(
            name='Quota',
        ),
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.UniqueConstraint(fields=('organisations', 'type_organisations', 'checking'), name='unique_ratings'),
        ),
    ]
