# Generated by Django 4.0.5 on 2023-02-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0048_ratings_delete_quota_ratings_unique_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип шаблона')),
            ],
            options={
                'verbose_name': 'Тип шаблона',
                'verbose_name_plural': 'Типы шаблонов',
            },
        ),
        migrations.AlterField(
            model_name='organisations',
            name='inn',
            field=models.CharField(blank=True, default=1, max_length=12, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisations',
            name='kpp',
            field=models.CharField(blank=True, default=1, max_length=9, verbose_name='КПП'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisations',
            name='ogrn',
            field=models.CharField(blank=True, default=1, max_length=15, verbose_name='ОГРН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templates',
            name='type_templates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.type_templates', verbose_name='Тип шаблона'),
        ),
    ]
