# Generated by Django 4.0.5 on 2023-02-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0051_form_sections_employ_in_act_form_sections_rating_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_sections',
            name='rating_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ключ для рейтингов'),
        ),
    ]
