# Generated by Django 4.0.5 on 2023-02-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0052_alter_form_sections_rating_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_sections',
            name='raring_order_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер рейтинга'),
        ),
    ]
