# Generated by Django 4.0.5 on 2023-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0053_form_sections_raring_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficients',
            name='main_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Коэффициенты законодательные'),
        ),
        migrations.AlterField(
            model_name='coefficients',
            name='points_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Баллы законодательные'),
        ),
        migrations.AlterField(
            model_name='coefficients',
            name='respondents_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Коэффициенты рандомные, для респондентов'),
        ),
    ]
