# Generated by Django 4.0.5 on 2023-02-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0054_alter_coefficients_main_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_values',
            name='special_option',
            field=models.BooleanField(default=False, verbose_name='Признак альтернативной опции ответа'),
        ),
        migrations.AlterField(
            model_name='question_values',
            name='name_alternativ',
            field=models.CharField(blank=True, max_length=100, verbose_name='Второй вариант ответа'),
        ),
    ]
