# Generated by Django 4.0.5 on 2023-03-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0055_question_values_special_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.comments', verbose_name='Комментарий эксперта'),
        ),
    ]
