# Generated by Django 4.0.5 on 2023-05-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0058_alter_list_checking_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_organisation_persons',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='form_organisation_persons',
            name='person',
        ),
        migrations.RemoveConstraint(
            model_name='organisation_persons',
            name='unique_person',
        ),
        migrations.AddField(
            model_name='organisation_persons',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.organisations', verbose_name='Учреждение'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='department_persons',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='website',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organisation_persons',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='website',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='Form_Organisation_Persons',
        ),
    ]
