# Generated by Django 4.0.5 on 2023-06-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0059_remove_form_organisation_persons_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='latitude',
            field=models.FloatField(max_length=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='organisations',
            name='longitude',
            field=models.FloatField(max_length=10, null=True, verbose_name='Долгота'),
        ),
    ]
