# Generated by Django 4.0.5 on 2023-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0061_regions_area_geojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='district_geojson',
            field=models.CharField(max_length=100, null=True, verbose_name='Районы региона в формате GeoJson'),
        ),
    ]
