# Generated by Django 4.0.5 on 2023-07-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0063_alter_organisations_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код региона'),
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Район региона')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Код района')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Признак удаления')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Районы регионов',
                'verbose_name_plural': 'Районы регионов',
            },
        ),
        migrations.AddField(
            model_name='organisations',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklist.districts', verbose_name='Район региона'),
        ),
    ]
