# Generated by Django 4.0.5 on 2023-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0065_districtarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districts',
            options={'verbose_name': 'Административно-территориальное деление', 'verbose_name_plural': 'Административно-территориальное деление'},
        ),
        migrations.RemoveField(
            model_name='districts',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='districts',
            name='region',
        ),
        migrations.RemoveField(
            model_name='organisations',
            name='district',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='code',
        ),
        migrations.AddField(
            model_name='organisations',
            name='okato',
            field=models.CharField(blank=True, max_length=11, verbose_name='Район региона'),
        ),
        migrations.AddField(
            model_name='regions',
            name='okato',
            field=models.CharField(blank=True, max_length=11, verbose_name='Район региона'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код ОКАТО'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
