# Generated by Django 4.0.5 on 2023-08-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0066_alter_districts_options_remove_districts_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='okato',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Район региона'),
        ),
    ]
