# Generated by Django 4.0.5 on 2023-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0068_alter_regions_okato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='okato',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='ОКАТО'),
        ),
    ]
