# Generated by Django 4.0.5 on 2023-08-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0069_alter_organisations_kpp_alter_organisations_okato'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='region_id',
            field=models.IntegerField(default=99, verbose_name='Код региона из модели регионов'),
            preserve_default=False,
        ),
    ]
