# Generated by Django 4.0.5 on 2023-08-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0069_alter_organisations_kpp_alter_organisations_okato'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation_persons',
            name='use_default',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
