from .answers import Answers
from .checking import Checking
from .comments import Comments
from .coefficients import Coefficients
from .department_persons import Department_Persons
from .departments import Departments
from .form_sections import Form_Sections
from .form_sections_question import Form_Sections_Question
from .form_type_organisation import Form_Type_Organisation
from .forms_act import FormsAct
from .forms_recommendations import Forms_Recommendations
from .list_checking import List_Checking
from .organisation_persons import Organisation_Persons
from .organisations import Organisations
from .photo import Photo
from .question_values import Question_Values
from .questions import Questions
from .ratings import Ratings
from .recommendations import Recommendations
from .regions import Regions
from .signed_dociuments import Signed_Dociuments
from .templates import Templates
from .transaction_exchange import Transaction_Exchange
from .type_answers import Type_Answers
from .type_departments import Type_Departments
from .type_organisations import Type_Organisations
from .versions import Versions
from .profile import Profile
from .profile_position import Profile_Position
from .districts import Districts